# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u56de\u7b54')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User', verbose_name='\u56de\u7b54\u8005')),
            ],
            options={
                'verbose_name': '\u7b54\u6848',
                'verbose_name_plural': '\u7b54\u6848',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='\u95ee\u9898\u9648\u8ff0')),
                ('number_of_answer', models.IntegerField(default=0, verbose_name='\u56de\u7b54\u6570')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User', verbose_name='\u63d0\u95ee\u8005')),
            ],
            options={
                'verbose_name': '\u95ee\u9898',
                'verbose_name_plural': '\u95ee\u9898',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question.Question', verbose_name='\u95ee\u9898'),
        ),
    ]
